#!/usr/bin/env bash

# --- CONFIG ---

# Specified the dotfiles to install here
SINGLE_DOTS="default scripts"
FOLDER_DOTS="shell wayland-env wayland-sway"

# --- VARIABLES ---

DOTFILES="$HOME/dotfiles"
GIT="git --git-dir=$DOTFILES/.git --work-tree=$DOTFILES"
STOW="stow --dotfiles --dir=$DOTFILES --target=$HOME"

# --- FUNCTIONS ---

function show_usage {
	echo "Usage: stow-dots [help] [sync|push|both] [list] [fix] [install]"
}

function sync {
	echo "> Syncing..."
	$STOW --no-folding \
		$SINGLE_DOTS
	$STOW \
		$FOLDER_DOTS

	# check if stow return error
	if [ $? -ne 0 ]; then
		echo "ERROR: Stow threw a error"
		exit 1
	fi

	echo "> Completed dotfiles sync"
}

function push {
	echo "> Starting git"

	# push to my github account
	$GIT add .
	$GIT commit -m "update"
	$GIT push

	# check if git return error
	if [ $? -ne 0 ]; then
		echo "ERROR: Git threw a error"
		exit 1
	fi

	echo "> Completed dotfiles push"
}

function list {
	ls $DOTFILES --group-directories-first --color
}

function fix_links {
	echo "> Searching and fixing broken symlinks..."
	find ${XDG_CONFIG_HOME:-$HOME/.config} -xtype l -delete
	find ${XDG_DATA_HOME:-$HOME/.local/share} -xtype l -delete
}

function install {
	fix_links
	echo ''

	echo "> That will restow your dots to make a fresh install. You are sure of proceed? (s/N)"
	read INPUT
	echo ''

	if [[ $INPUT = "s" || $INPUT = "S" ]]; then
		echo "Started installation."

		$STOW --restow --no-folding \
			$SINGLE_DOTS
		$STOW --restow \
			$FOLDER_DOTS

		echo "> Completed installation"
	else
		echo "> Cancelled"
	fi
}

# main
case "$1" in
	help)
		show_usage
		;;
	sync)
		sync
		;;
	push)
		push
		;;
	both)
		sync
		echo ''
		push
		;;
	list)
		list
		;;
	fix)
		fix_links
		;;
	install)
		install
		;;
	*)
		show_usage
		;;
esac
