theme = "monokai_pro"

[editor]
auto-format = true

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[editor.indent-guides]
render = false
character = "┆" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1