[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff-lsp]
command = "ruff-lsp"

[[language]]
name = "python"
roots = ["pyproject.toml"]
file-types = ["py"]
comment-token = "#"
language-servers = ["pyright", "ruff-lsp"]
formatter = {command = "ruff", args = ["format", "--quiet", "-"]}
auto-format = true

[[language]]
name = "rust"
formatter = {command = "rustfmt"}
