# Python
[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
formatter = {command = "ruff", args = ["format", "--quiet", "-"]}
auto-format = true

# Rust
[[language]]
name = "rust"
formatter = {command = "rustfmt"}
