[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[[language]]
name = "python"
roots = ["pyproject.toml"]
file-types = ["py"]
comment-token = "#"
language-servers = ["pyright"]
formatter = {command = 'black', args = ["--quiet", "-"]}
auto-format = true
